# Generated by Django 5.2 on 2025-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowfree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='dots',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='Dot',
        ),
    ]
