# Generated by Django 5.2 on 2025-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowfree', '0002_gameboard_dots_delete_dot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='dots',
            field=models.JSONField(default=list),
        ),
    ]
